# Generated by Django 2.2.6 on 2019-10-08 11:48

from django.db import migrations, models
import person.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.PositiveIntegerField(default=0, verbose_name='Skills')),
                ('hero_id', models.PositiveIntegerField(default=0, verbose_name='Heros')),
            ],
            bases=(models.Model, person.models.ConfigModel),
        ),
        migrations.CreateModel(
            name='Heros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='角色名')),
                ('hp', models.PositiveIntegerField(default=0, verbose_name='血量')),
            ],
            bases=(models.Model, person.models.ConfigModel),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='角色名')),
                ('attack', models.PositiveIntegerField(default=0, verbose_name='攻击力')),
                ('status', models.CharField(choices=[('can_use', 'can_use')], default='can_use', max_length=20, verbose_name='状态')),
            ],
            bases=(models.Model, person.models.ConfigModel),
        ),
    ]
